include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # General Dart/Flutter best practices
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true
    prefer_is_empty: true
    avoid_function_literals_in_foreach_calls: true
    require_trailing_commas: true
    await_only_futures: true
    avoid_futureor_void: true
    avoid_void_async: true
    sort_pub_dependencies: true

    # Null safety and type checks
    avoid_null_checks_in_equality_operators: true

    # Naming conventions
    avoid_classes_with_only_static_members: true
    always_use_package_imports: true
    camel_case_extensions: true
    library_prefixes: true

    # Documentation
    # public_member_api_docs: true
    always_put_control_body_on_new_line: true
    slash_for_doc_comments: true

    # Widget optimization
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    prefer_mixin: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

    # Error handling
    only_throw_errors: true

    # Imports
    avoid_relative_lib_imports: true
    implementation_imports: true

    # Others
    prefer_const_declarations: true
    prefer_final_locals: true
    use_late_for_private_fields_and_variables: true
